### ISSUE TITLE
Push the application to Bluemix

### ISSUE THREAD

**Issue by ilanasufrin** [ilanasufrin/nyu-devops-homework-1#11]
As a developer
I want to push the application to Bluemix
So that I can visit an external URL and see the running application properly

**Acceptance Criteria**
`I want to be able to visit a URL`
`And see the running application`
`This includes QAing all the methods`

Hint: use `cf push`

**Comment by Cantal0p3** [comment]
assigning to  @ilanasufrin since the bluemix app was created with her bluemix account.

**Comment by ilanasufrin** [comment]
we can both be assigned @Cantal0p3 since you're doing the QA :-)

**Comment by ilanasufrin** [comment]
I'll push it as soon as we're unblocked by other tickets, specifically https://github.com/ilanasufrin/nyu-devops-homework-1/issues/7

**Comment by Cantal0p3** [comment]
I pushed the changes to bluemix - http://nyu-devops-as1-icecream-project.mybluemix.net/.
Did a round of testing for List All, List one, add, update, and delete. Running as expected.

**Comment by ilanasufrin** [comment]
Our app is deployed here http://devops-icecream.mybluemix.net/

woohoo ~~~~
