### ISSUE TITLE
Query Ice Cream Flavor by some attribute of the Resource

### ISSUE THREAD

**Issue by skyline220** [ilanasufrin/nyu-devops-homework-1#12]
As a developer
I need to create a RESTful way to query an ice cream flavor by some attribute of an ice cream flavor resource
So that my team members can query an ice cream flavor by some attribute of an ice cream flavor resource

Acceptance Criteria
After I SSH using the Vagrant file
I can query an ice cream flavor by some attribute of an ice cream flavor resource

**Comment by skyline220** [comment]
I worked on this one but am not familiar at all with Python. Does anyone see example code for this type of query? Other than the Query structure itself which I see in the slides

**Comment by rofrano** [comment]
@skyline220 The example code for doing a query is in the `nyu-lab-restful-flask` project code base. The `list_pets()` method is processing `kind` as a possible query parameter.

**Comment by ilanasufrin** [comment]
I think @Cantal0p3 might have done this just now in the PR I just reviewed?
https://github.com/ilanasufrin/nyu-devops-homework-1/pull/28

**Comment by skyline220** [comment]
Sounds good Ill use that sample code as an example

**Comment by skyline220** [comment]
I finished this and unit tested with the file, its similar to the list_pets() method by Professor Rofrano in the nyu-lab-restful-flask
