### ISSUE TITLE
Change Status of Ice cream

### ISSUE THREAD

**Issue by sschweber** [ilanasufrin/nyu-devops-homework-1#13]
As a developer
I need to create a service
So that someone can melt of freeze an ice cream flavor

Acceptance Criteria:
`When I vagrant up`
`I should be able to decide to melt or freeze an ice cream flavor based personal preference`

**Comment by skyline220** [comment]
Do you guys know about the app_route? The one in the method signatures is different from the one Sydney used. I used the one currently in the method signature for this.

**Comment by Cantal0p3** [comment]
I have added a new method get_popular_ice_cream(), which reads argument from the request url like http://localhost:5000/ice-creams?popularity=4.
You can check that out. It is in the branch fetch-icecream-by-popularity.

**Comment by skyline220** [comment]
Done, please see the new ticket I added titled redundant GET methods as I discovered an issue while testing this code

**Comment by Cantal0p3** [comment]
#77
