### ISSUE TITLE
Create a Cloud Foundry application in Bluemix

### ISSUE THREAD

**Issue by ilanasufrin** [ilanasufrin/nyu-devops-homework-1#3]
As a developer
I want to create a Cloud Foundry application
So that I can deploy my application to IBM's Bluemix

**Acceptance Criteria**
`When I go to the Bluemix website`
`Then I should see a running Bluemix application`
`And I should share the SDK with my other team members`

**Comment by ilanasufrin** [comment]
http://devops-icecream.mybluemix.net/

**Comment by ilanasufrin** [comment]
https://github.com/ilanasufrin/nyu-devops-homework-1/pull/33

**Comment by Cantal0p3** [comment]
Created the app - http://nyu-devops-as1-icecream-project.mybluemix.net/
