### ISSUE TITLE
Create manifest.yml, Procfile,and  runtime.txt files

### ISSUE THREAD

**Issue by ilanasufrin** [ilanasufrin/nyu-devops-homework-1#7]
As a developer,
I want to create `manifest.yml`, `Procfile`, and  `runtime.txt` files
So that Bluemix will know how to deploy my application

**Acceptance Criteria**

**Comment by skyline220** [comment]
Can anyone help me get this done? I have a family issue that came up for tomorrow and there's no way I can get this done in time. I can't even match the slides online with the actual BlueMix and I already took on a lot making that entire unit test file. If someone could help me finish this I'd really appreciate it.

**Comment by Cantal0p3** [comment]
I made the necessary changes.

**Comment by ilanasufrin** [comment]
I also made the necessary changes so I think this ticket is done
