### ISSUE TITLE
BUG: Cannot call Query method

### ISSUE THREAD

**Issue by rofrano** [ilanasufrin/nyu-devops-homework-1#82]
The query function doesn't work because the method:
```
@app.route('/ice-creams/<id>', methods=['GET'])
def list_resources_by_type():
```
Is hidden by the get method:
```
@app.route('/ice-creams/<id>', methods=['GET'])
def get_an_ice_cream(id):
```
Because their URL mapping:
```
@app.route('/ice-creams/<id>', methods=['GET'])
```
is the same! 

Also, the query method should not have an `id` after it. An `id` will always return one resource while a query should return many. It therefore needs to map to `/ice-creams` instead.

To fix this you need one method that maps to:
```
@app.route('/ice-creams', methods=['GET'])
```
that handles both query and non-query scenario. An example of how to handle this can be seen in the [rofrano/nyu-lab-bdd-tdd](https://github.com/rofrano/nyu-lab-bdd-tdd) project. 

Please label this as a bug and, in general, this project should use more labels to identify stories properly.

**Comment by Cantal0p3** [comment]
#93
