### ISSUE TITLE
Root URL should document Query and Action API's

### ISSUE THREAD

**Issue by rofrano** [ilanasufrin/nyu-devops-homework-1#83]
**Expected Behavior**
- When I visit the root URL '/' I expect to see API documentation for the resources, query, and action calls

**Existing Behavior**
- When I visit the root URL '/' I only see API documentation for the resource
- Query and Action API documentation is missing

**Suggested Fix**
- Add the Query and Action API documentation to the root url

**Comment by Cantal0p3** [comment]
pull request #80
